# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ed6749bdfd388b0b0000dcea94a39483fe83b0246b3a0d9102aa842d762ce6c1be9267c2cfd678378435b0f6a934ffcbdf6fcf19ef658e0ba1d468916040959

test:
  secret_key_base: ec0938d08e19ecb47010a038c66e839cb3a0becc08a54403414a87d243624c26c87cc3257bdab75600fc703763eb1a6f885c6abe97d7084e4f49d5e7b5486e8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
